# Site settings
title: 'ditikos.github.io' # Your Title
tagline: 'Think &middot; Build &middot; Publish' # A brief tagline for your site
sidebar_image: /images/zx-spectrum.jpg

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
#baseurl: /

future: true